'use strict';
const main=document.getElementById('main'),dialog=document.getElementById('course-dialog');
const KEY='mech-robotics-learning-v1';
let state={courses:{},projects:{}},storageAvailable=true,currentCourse=null;
try{const raw=localStorage.getItem(KEY);if(raw){const value=JSON.parse(raw);if(value&&typeof value==='object'&&!Array.isArray(value))state={courses:value.courses&&typeof value.courses==='object'?value.courses:{},projects:value.projects&&typeof value.projects==='object'?value.projects:{}};}}catch{storageAvailable=false;}
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const getCourse=id=>COURSES.find(c=>c.id===id);
function record(id){const r=state.courses[id];return r&&typeof r==='object'?r:{};}
function pct(c){const checks=record(c.id).checks;return Array.isArray(checks)?Math.round(c.topics.filter((_,i)=>checks[i]===true).length/c.topics.length*100):0;}
function status(c){const p=pct(c),r=record(c.id);if(p===100)return 'done';if(r.started===false)return p>0?'paused':'new';return p>0||r.started===true?'in-progress':'new';}
const statusName=s=>({'new':'未开始','in-progress':'学习中','paused':'已暂停','done':'已掌握'}[s]);
function save(){try{localStorage.setItem(KEY,JSON.stringify(state));storageAvailable=true;return true;}catch{storageAvailable=false;toast('浏览器存储不可用，本次修改仅保留到页面关闭。');return false;}}
let toastTimer;function toast(message){const box=document.getElementById('toast');box.textContent=message;box.classList.add('visible');clearTimeout(toastTimer);toastTimer=setTimeout(()=>box.classList.remove('visible'),3500);}
function heading(title,description,tag=''){return `<div class="heading"><div><span class="eyebrow">MECHANICAL ENGINEERING / ROBOTICS</span><h1>${title}</h1><p>${description}</p></div>${tag?`<span class="quiet-tag">${tag}</span>`:''}</div>`;}
function courseLearningControls(c){const s=status(c),tab=s==='new'?'in-progress':s;const hints={'new':'加入后可在「我的学习 → 学习中」查看。','in-progress':'已在「我的学习 → 学习中」。取消后保留知识进度和笔记。','paused':'已在「我的学习 → 已暂停」。可随时重新加入学习中。','done':'知识任务已完成，已在「我的学习 → 已掌握」。'};return `<span class="badge ${s}">${statusName(s)} · ${pct(c)}%</span><p>${hints[s]}</p><div class="learning-control-actions"><button class="button ${s==='in-progress'?'secondary':''}" data-toggle-learning="${esc(c.id)}" aria-pressed="${s==='in-progress'}" ${s==='done'?'disabled':''}>${s==='in-progress'?'取消学习中':s==='paused'?'重新加入学习中':s==='done'?'已掌握':'加入学习中'}</button><a class="text-link" data-learning-link href="#learning?status=${tab}">查看我的学习</a></div><p class="fine">个人路线中的连线模块需在「成长路线 → 我的个人路线」单独添加。</p>`;}
function updateCourseLearningControls(){const c=getCourse(currentCourse),box=document.getElementById('course-learning-controls');if(c&&box)box.innerHTML=courseLearningControls(c);}
function setCourseLearning(id,active){const c=getCourse(id);if(!c||status(c)==='done')return;state.courses[id]={...record(id),started:active};const persisted=save();render();if(dialog.open&&currentCourse===id)updateCourseLearningControls();if(persisted)toast(active?'已加入：我的学习 → 学习中':pct(c)>0?'已移至：我的学习 → 已暂停，进度和笔记保留':'已取消学习中，仍可在课程地图查看');}
function learningLocation(){const count=COURSES.filter(c=>status(c)==='in-progress').length;return `<section class="panel learning-location"><div><h2>我的学习 <span class="learning-total">${count} 门学习中</span></h2><p>加入学习中的课程集中显示在这里；有进度的课程取消后进入「已暂停」，完成全部任务后进入「已掌握」。</p></div><a class="button secondary" href="#learning">查看我的学习</a></section>`;}
function learning(){const params=new URLSearchParams(location.hash.split('?')[1]||'');const requested=params.get('status');const tab=['in-progress','paused','done'].includes(requested)?requested:'in-progress';const tabs=[['in-progress','学习中'],['paused','已暂停'],['done','已掌握']];const selected=COURSES.filter(c=>status(c)===tab);main.innerHTML=heading('我的学习','这里集中显示当前浏览器记录的课程。取消学习中保留知识进度和笔记。')+`<div class="chips learning-tabs" aria-label="按课程学习状态查看">${tabs.map(([s,label])=>`<button class="chip ${tab===s?'selected':''}" aria-pressed="${tab===s}" data-learning-tab="${s}">${label} <strong>${COURSES.filter(c=>status(c)===s).length}</strong></button>`).join('')}</div><p class="learning-list-hint">${tab==='in-progress'?'在课程详情点击「加入学习中」，课程会出现在本页；首次记录知识任务也会进入学习中；已取消的课程请手动重新加入。':tab==='paused'?'这些课程取消了学习中，已有进度仍保留；点击课程可重新加入。':'这些课程已完成全部知识任务，自动归入已掌握。'} 仅加入列表不会自动添加个人路线模块。</p><p class="result-count" aria-live="polite">${statusName(tab)}：${selected.length} 门</p>${selected.length?`<div class="course-grid">${selected.map(c=>card(c)).join('')}</div>`:`<div class="empty">${tab==='in-progress'?'还没有学习中的课程。':tab==='paused'?'没有已暂停的课程。':'还没有完成全部知识任务的课程。'}<br><a class="button secondary" href="#courses" style="margin-top:16px">前往课程地图</a></div>`}<div class="learning-route-location"><strong>个人路线里的模块在哪里？</strong><p>通过画布「添加课程／自定义模块」添加的节点，在「成长路线 → 我的个人路线」查看和连线。个人路线记录与课程学习状态分别保存。</p><a class="text-link" href="#roadmap">查看我的个人路线</a></div>`;}
function resourceKeys(c){return [...new Set([c.resource,...(c.alternatives||[]),...(c.extra||[])])].filter(k=>RESOURCES[k]);}
function courseSearchText(c){return [c.name,c.en,c.description,...c.topics,...resourceKeys(c).flatMap(k=>{const r=RESOURCES[k];return [r[0],r[2],r[3]?.platform||'',r[3]?.basis||''];})].join(' ').toLowerCase();}
function prerequisiteHint(c){const missing=c.prereqs.filter(id=>{const p=getCourse(id);return p&&status(p)!=='done';});return missing.length?'<p class="prerequisite-hint">建议先修 '+missing.length+' 门 · 可在详情中查看</p>':'<p class="prerequisite-hint ready-hint">先修已满足 · 可开始学习</p>';}
function videoGroups(c,platform='all'){const seen=new Set();const groups=[['主课程',[c.resource]],['备选课程',c.alternatives||[]],['专题补充',c.extra||[]]].map(([label,keys])=>({label,keys:keys.filter(k=>{if(seen.has(k)||!RESOURCES[k])return false;seen.add(k);return platform==='all'||RESOURCES[k][3]?.platform===platform;})}));const count=groups.reduce((n,g)=>n+g.keys.length,0);return '<p class="fine" aria-live="polite">显示 '+count+' / '+resourceKeys(c).length+' 个视频入口</p>'+(count?groups.filter(g=>g.keys.length).map(g=>(g.label==='主课程'?'':'<h4 class="video-heading">'+g.label+'</h4>')+g.keys.map(k=>videoResource(k,g.label)).join('')).join(''):'<p class="fine">这门课程暂无此平台的资源，可以切换平台查看。</p>');}
function filterCourseVideos(platform){const c=getCourse(currentCourse);if(!c)return;document.getElementById('video-results').innerHTML=videoGroups(c,platform);dialog.querySelectorAll('[data-video-platform]').forEach(b=>{const selected=b.dataset.videoPlatform===platform;b.classList.toggle('selected',selected);b.setAttribute('aria-pressed',String(selected));});}
function videoCount(c){return new Set([c.resource,...(c.alternatives||[]),...(c.extra||[])]).size;}
function videoResource(key,label){const r=RESOURCES[key];if(!r)return '';const m=r[3]||{};return `<a class="resource-link" href="${esc(r[1])}" target="_blank" rel="noopener noreferrer"><span class="video-top"><span class="video-tag">${esc(m.platform||'视频')}</span><span class="video-role">${esc(label)}</span>${m.popularity?`<span class="video-popularity">${esc(m.popularity)}</span>`:''}</span><strong>${esc(r[0])}</strong><small>${esc(r[2])}</small><small class="video-evidence">选课参考：${esc(m.basis)}${m.popularity?' · 检索快照 '+esc(m.date):''}</small><span class="video-open">前往原平台观看 ↗</span></a>`;}
function courseVideos(c){return `<h3>中文视频课程 <span class="fine">${videoCount(c)} 个入口</span></h3><p class="fine">优先完整的高校课程与原作者系列，再结合热度选择适合自己的讲法。主课、备选课可任选一套学习；专题补充按需观看。</p><div class="chips video-platform-filters" aria-label="按视频平台筛选"><button class="chip selected" aria-pressed="true" data-video-platform="all">全部平台</button><button class="chip" aria-pressed="false" data-video-platform="MOOC">MOOC</button><button class="chip" aria-pressed="false" data-video-platform="B站">B站</button></div><div id="video-results">${videoGroups(c)}</div><p class="fine video-snapshot">播放量、评分与评价数来自 ${VIDEO_LIBRARY.updated} 检索到的页面快照，非实时统计；MOOC 参课人数与 B站播放量口径不同。热度与课程认证仅辅助选课。MOOC 可能需登录、选课，历史学期可选最新开课；观看和收费条件以原平台为准。</p>`;}
function card(c){return `<article class="course-card"><div class="card-meta"><span class="category">${GROUPS[c.group]}</span><span class="badge ${status(c)}">${statusName(status(c))}</span></div><div class="course-icon" aria-hidden="true">${c.icon}</div><h3>${esc(c.name)}</h3><p class="english">${c.en}</p><p class="description">${c.description}</p>${prerequisiteHint(c)}<div class="card-bottom"><span>${c.kind} · 阶段 ${c.phase+1}<small class="video-count">${videoCount(c)} 个中文视频入口</small></span><button class="card-open" data-course="${c.id}" aria-label="学习${esc(c.name)}">${status(c)==='done'?'查看课程':status(c)==='new'?'开始学习':'继续学习'}</button></div><div class="bar" role="progressbar" aria-label="${esc(c.name)}学习进度" aria-valuemin="0" aria-valuemax="100" aria-valuenow="${pct(c)}"><span style="width:${pct(c)}%"></span></div>${['in-progress','paused'].includes(status(c))?`<div class="course-queue-actions"><button class="card-open" data-toggle-learning="${esc(c.id)}">${status(c)==='in-progress'?'取消学习中':'重新加入学习中'}</button></div>`:''}</article>`;}
function stages(){return `<div class="stage-strip">${PHASES.map((p,i)=>{const all=COURSES.filter(c=>c.phase===i),done=all.filter(c=>status(c)==='done').length;const first=PHASES.findIndex((_,j)=>COURSES.some(c=>c.phase===j&&status(c)!=='done'));return `<button class="stage ${first===i?'current':''}" data-phase="${i}"><span class="stage-number">PHASE 0${i+1}</span><strong>${p.name}</strong><p>${p.tag}</p><em>${done} / ${all.length} 门课程已掌握</em></button>`;}).join('')}</div>`;}
function ready(c){return c.prereqs.every(id=>{const p=getCourse(id);return p&&status(p)==='done';});}
function home(){const done=COURSES.filter(c=>status(c)==='done').length,active=COURSES.filter(c=>status(c)==='in-progress');const avg=Math.round(COURSES.reduce((v,c)=>v+pct(c),0)/COURSES.length);const candidates=[...active,...COURSES.filter(c=>status(c)==='new'&&ready(c))];const chosen=candidates[0]||COURSES.find(c=>status(c)!=='done')||COURSES[0];const recommended=candidates.length?candidates.slice(0,3):COURSES.slice(0,3);main.innerHTML=heading('学习工作台','中文视频为主，按学习路线把课程知识用到机器人项目。','机械工程 · 机器人方向')+learningLocation()+`<div class="overview"><section class="focus-panel"><span class="eyebrow">${done===COURSES.length?'学习路线已完成':'下一步学习'}</span><span class="mini-number" aria-hidden="true">0${chosen.phase+1}</span><h2>${chosen.name}</h2><p>${chosen.task}</p><button class="button" data-course="${chosen.id}">进入课程</button></section><section class="stats-panel"><div class="stats-top"><h2>我的学习进度</h2><span>按知识任务计算</span></div><div class="stats-value">${avg}%<small>总体完成</small></div><div class="bar" role="progressbar" aria-label="总体学习进度" aria-valuemin="0" aria-valuemax="100" aria-valuenow="${avg}"><span style="width:${avg}%"></span></div><div class="stats-caption">${done} / ${COURSES.length} 门课程已掌握</div><div class="stats-bottom"><a class="stats-learning-link" href="#learning"><b>${active.length}</b><span>正在学习 · 查看</span></a><div><b>${Object.values(state.courses).filter(r=>r?.note?.trim()).length}</b><span>课程笔记</span></div><div><b>${PROJECTS.filter(p=>state.projects[p.id]===true).length}</b><span>完成项目</span></div></div></section></div><div class="section-title"><h2>你的成长路径<small>四个阶段，逐步连接</small></h2><a class="text-link" href="#roadmap">查看路线</a></div>${stages()}<div class="section-title"><h2>建议现在学习<small>优先继续已开始的课程</small></h2><a class="text-link" href="#courses">浏览全部课程</a></div><div class="course-grid">${recommended.map(card).join('')}</div>`;}
let category=0,query='',progressFilter='all',readinessFilter='all';
function courses(){main.innerHTML=heading('课程地图','每门课程提供多套中文视频选择；参考高校、发布者、播放量和课程评价选学。',`${COURSES.length} 门课程 · ${VIDEO_LIBRARY.resourceCount} 个视频资源`)+`<div class="filters"><label class="searchbox"><span aria-hidden="true">⌕</span><input id="search" type="search" placeholder="搜索课程、知识点、讲师或视频来源" aria-label="搜索课程" value="${esc(query)}"></label><select id="progress-filter" aria-label="按学习状态筛选"><option value="all">全部学习状态</option><option value="new">未开始</option><option value="in-progress">学习中</option><option value="paused">已暂停</option><option value="done">已掌握</option></select><select id="readiness-filter" aria-label="按先修情况筛选"><option value="all">全部先修情况</option><option value="ready">先修已满足</option><option value="missing">有建议先修</option></select></div><div class="chips" aria-label="课程分类">${GROUPS.map((g,i)=>`<button class="chip ${category===i?'selected':''}" aria-pressed="${category===i}" data-category="${i}">${g}</button>`).join('')}</div><div id="course-results"></div>`;document.getElementById('progress-filter').value=progressFilter;document.getElementById('readiness-filter').value=readinessFilter;document.getElementById('readiness-filter').addEventListener('change',e=>{readinessFilter=e.target.value;filterCourses();});document.getElementById('search').addEventListener('input',e=>{query=e.target.value;filterCourses();});document.getElementById('progress-filter').addEventListener('change',e=>{progressFilter=e.target.value;filterCourses();});filterCourses();}
function filterCourses(){const q=query.trim().toLowerCase();const filtered=COURSES.filter(c=>(category===0||c.group===category)&&(progressFilter==='all'||status(c)===progressFilter)&&(readinessFilter==='all'||(readinessFilter==='ready'?ready(c):!ready(c)))&&courseSearchText(c).includes(q));document.getElementById('course-results').innerHTML=`<p class="result-count" aria-live="polite">共 ${filtered.length} 门课程</p>`+(filtered.length?`<div class="course-grid">${filtered.map(card).join('')}</div>`:`<div class="empty">没有找到符合条件的课程。<br>试试其他关键词或学习状态。</div>`);}
function recommendedRoboticsRoute(){
const route=RECOMMENDED_ROBOTICS_ROUTE;
return `<section class="panel recommended-route" id="recommended-robotics-route" aria-labelledby="recommended-route-title">
<div class="recommended-route-header"><span class="eyebrow">RECOMMENDED PATH / 参考路线</span><h2 id="recommended-route-title">${esc(route.title)}</h2><p>${esc(route.intro)}</p></div>
<p class="route-method">这条顺序是本站根据你的背景作出的推荐。第 1 步与机械复习可以并行；已有基础可按实践成果补缺，第 4、5 步也可交叉推进。按成果进入下一步，不设统一完成月数。</p>
<ol class="recommended-steps">${route.steps.map((step,i)=>`<li class="recommended-step"><span class="recommended-step-number" aria-hidden="true">${String(i+1).padStart(2,'0')}</span><div><h3>${esc(step.name)}</h3><p class="recommended-focus">${esc(step.focus)}</p><div class="recommended-deliver"><strong>阶段成果</strong><p>${esc(step.deliver)}</p></div><div class="course-links" aria-label="${esc(step.name)}的中文视频课程">${step.courses.map(id=>`<button data-course="${esc(id)}">${esc(getCourse(id).name)}</button>`).join('')}</div><p class="recommended-basis">路线依据：${step.basis.map(n=>`<a href="${esc(route.sources[n].url)}" target="_blank" rel="noopener noreferrer">${esc(route.sources[n].name)}</a>`).join(' · ')}</p></div></li>`).join('')}</ol>
<div class="recommended-next"><h3>完成主线后，再选一个方向深入</h3><p><strong>机电与控制：</strong>嵌入式、驱动、机构优化与实时控制；<strong>自主导航：</strong>状态估计、SLAM 与规划；<strong>视觉感知：</strong>标定、识别与三维感知；<strong>机械臂：</strong>动力学、轨迹优化与操作。先完成一个系统项目，再根据兴趣与岗位要求选择。</p><p>工程材料、制造、流体与传热等学校课程并行学习；在选材、工艺、气动或热管理项目中进一步应用。AutoCAD 可随制图任务补充，SolidWorks 用于这条主线的三维设计。</p><p class="fine">点击各阶段课程按钮，可查看现有的中文 MOOC / B站视频、知识任务与笔记。</p><a class="text-link" href="#projects">进入项目实践 →</a></div>
<div class="recommended-sources"><h3>整理依据与原始来源</h3><p class="fine">整理于 ${esc(route.updated)}。以下来源提供课程框架与技术学习顺序，七步路线由本站综合编排；部分原文为英文，实际课程入口仍以中文视频为主。</p><ul>${route.sources.map(s=>`<li><a class="text-link" href="${esc(s.url)}" target="_blank" rel="noopener noreferrer">${esc(s.name)} ↗</a><p>${esc(s.use)}</p></li>`).join('')}</ul></div>
</section>`;
}
function roadmap(){main.innerHTML=heading('成长路线','已有基础可以直接标记任务；先修关系用于提示，不限制你学习。')+personalRouteSection()+`<div class="route-note">建议同时保留一条机械课程主线与一条编程主线。学校课程、软件版本与个人基础不同，可以调整顺序；“专业必修”等标记为本站分类。</div>`+PHASES.map((p,i)=>`<section class="panel route-phase"><aside><span class="eyebrow">PHASE 0${i+1}</span><h2>${p.name}</h2><p>${p.desc}</p><p><strong>${p.deliver}</strong></p></aside><div class="route-courses">${COURSES.filter(c=>c.phase===i).map(c=>`<button class="route-item" data-course="${c.id}"><span>${c.name}</span><span class="badge ${status(c)}">${statusName(status(c))}</span></button>`).join('')}</div></section>`).join('')+recommendedRoboticsRoute();}
function projects(){main.innerHTML=heading('项目实践','每个项目都需要留下可复现的设计、代码与验证记录。',`${PROJECTS.length} 个综合项目`)+`<div class="project-grid">${PROJECTS.map((p,i)=>`<article class="project-card"><span class="eyebrow">PROJECT 0${i+1} · ${p.level}</span><h2>${p.name}</h2><p>${p.desc}</p><div class="course-links">${p.courses.map(id=>`<button data-course="${id}">${getCourse(id).name}</button>`).join('')}</div><ul>${p.deliverables.map(d=>`<li>${d}</li>`).join('')}</ul><a class="text-link" href="${p.url}" target="_blank" rel="noopener noreferrer">查看中文视频参考</a><div class="project-actions"><label><input type="checkbox" data-project="${p.id}" ${state.projects[p.id]===true?'checked':''}>已完成并留下验证记录</label></div></article>`).join('')}</div>`;}
function sources(){main.innerHTML=heading('开源参考','参考课程组织与工程实践，建立适合机械学生的学习路径。','调研于 2026-10-01')+`<p class="source-note">课程页以中文视频作为学习入口。以下开源项目用于参考学习路线、算法与系统组成；GitHub 原仓库可能使用英文。本站任务与路线独立编写，视频在原平台观看。</p><div class="source-grid">${SOURCES.map(s=>`<article class="source-card"><span class="type">${s.type}</span><h2>${s.name}</h2><p>${s.desc}</p><p class="reference"><strong>本站参考：</strong>${s.use}</p><a class="text-link" href="${s.url}" target="_blank" rel="noopener noreferrer">访问原始来源</a></article>`).join('')}</div>`;}
function notes(){const entries=COURSES.filter(c=>typeof record(c.id).note==='string'&&record(c.id).note.trim());main.innerHTML=heading('我的笔记','把公式、踩坑与实验结果，留在对应的课程里。',`${entries.length} 篇笔记`)+(entries.length?entries.map(c=>`<article class="note-card"><h2><button class="card-open" data-course="${c.id}">${c.name}</button></h2><p>${esc(record(c.id).note)}</p>${record(c.id).updated?`<time>更新于 ${new Date(record(c.id).updated).toLocaleString('zh-CN')}</time>`:''}</article>`).join(''):`<div class="empty">还没有课程笔记。<br>进入任意课程，写下今天掌握的知识或待解决的问题。<br><a class="button" href="#courses" style="margin-top:18px">浏览课程</a></div>`);}
function render(){const route=location.hash.slice(1).split('?')[0]||'home';const pages={home,learning,courses,roadmap,projects,sources,notes};const actual=pages[route]?route:'home';document.querySelectorAll('[data-nav]').forEach(a=>{a.classList.toggle('active',a.dataset.nav===actual);if(a.dataset.nav===actual)a.setAttribute('aria-current','page');else a.removeAttribute('aria-current');});document.getElementById('breadcrumb').textContent={home:'学习工作台',learning:'我的学习',courses:'课程地图',roadmap:'成长路线',projects:'项目实践',sources:'开源参考',notes:'我的笔记'}[actual];pages[actual]();mountPersonalRoute();const learningCount=COURSES.filter(c=>status(c)==="in-progress").length;document.getElementById("learning-nav-count").textContent=learningCount;document.querySelector("[data-nav=learning]").setAttribute("aria-label","我的学习，"+learningCount+" 门学习中");if(!storageAvailable)main.insertAdjacentHTML('afterbegin','<div class="notice">当前浏览器存储不可用，学习记录仅在本次打开期间保留。</div>');}
function showCourse(id){const c=getCourse(id);if(!c)return;currentCourse=id;const r=record(id),res=RESOURCES[c.resource];document.getElementById('dialog-category').textContent=GROUPS[c.group]+' / 阶段 '+(c.phase+1);document.getElementById('dialog-content').className='dialog-content';document.getElementById('dialog-content').innerHTML=`<h2 id="dialog-title">${c.name}</h2><p>${c.description}</p><div class="lesson-info"><strong>学习成果</strong><br>${c.task}</div><section class="course-learning-controls" id="course-learning-controls">${courseLearningControls(c)}</section><h3>建议先修</h3><div class="course-links">${c.prereqs.length?c.prereqs.map(pid=>`<button data-course="${pid}">${getCourse(pid).name} · ${statusName(status(getCourse(pid)))}</button>`).join(''):'<span class="fine">无站内先修要求，可从这里开始。</span>'}</div><h3>知识任务 <span id="check-count" class="fine">${Math.round(pct(c)*c.topics.length/100)} / ${c.topics.length}</span></h3><div class="checklist">${c.topics.map((topic,i)=>`<label class="check-row ${r.checks?.[i]===true?'checked':''}"><input type="checkbox" data-check="${i}" ${r.checks?.[i]===true?'checked':''}><span>${topic}</span></label>`).join('')}</div><p class="fine">进度按已完成的知识任务计算；取消学习中不会清除任务或笔记。</p>${courseVideos(c)}${c.resourceNote?`<p class="fine">${c.resourceNote}</p>`:''}<h3><label for="course-note">课程笔记</label></h3><textarea id="course-note" class="note-area" placeholder="记录关键公式、实验参数、错误原因与下一步…">${esc(typeof r.note==='string'?r.note:'')}</textarea><div class="save-row"><small id="note-status">手动保存 · 仅保存在当前浏览器</small><button class="button" id="save-note">保存笔记</button></div>`;document.getElementById('save-note').addEventListener('click',()=>{const entry=record(id);state.courses[id]={...entry,note:document.getElementById('course-note').value,updated:Date.now()};const ok=save();document.getElementById('note-status').textContent=ok?'已保存在当前浏览器':'仅保留到页面关闭';render();if(ok)toast('课程笔记已保存');});if(!dialog.open)dialog.showModal();}
document.addEventListener('click',e=>{const toggle=e.target.closest('[data-toggle-learning]');if(toggle){const c=getCourse(toggle.dataset.toggleLearning);if(c)setCourseLearning(c.id,status(c)!=='in-progress');return;}const tab=e.target.closest('[data-learning-tab]');if(tab){location.hash='learning?status='+tab.dataset.learningTab;return;}if(e.target.closest('[data-learning-link]')&&dialog.open)closeCourse();});
document.addEventListener('click',e=>{const videoFilter=e.target.closest('[data-video-platform]');if(videoFilter){filterCourseVideos(videoFilter.dataset.videoPlatform);return;}const courseButton=e.target.closest('[data-course]');if(courseButton){if(dialog.open){const note=document.getElementById('course-note');if(note&&note.value!==String(record(currentCourse).note??'')){state.courses[currentCourse]={...record(currentCourse),note:note.value,updated:Date.now()};save();}}showCourse(courseButton.dataset.course);return;}const phase=e.target.closest('[data-phase]');if(phase){category=0;query='';location.hash='roadmap?phase='+phase.dataset.phase;return;}const chip=e.target.closest('[data-category]');if(chip){category=Number(chip.dataset.category);courses();}});
document.addEventListener('change',e=>{if(e.target.matches('[data-check]')){const id=currentCourse,c=getCourse(id),i=Number(e.target.dataset.check);const entry=record(id);const checks=c.topics.map((_,j)=>j===i?e.target.checked:entry.checks?.[j]===true);state.courses[id]={...entry,started:entry.started!==false,checks};save();e.target.closest('label').classList.toggle('checked',e.target.checked);document.getElementById('check-count').textContent=checks.filter(Boolean).length+' / '+c.topics.length;render();updateCourseLearningControls();}if(e.target.matches('[data-project]')){state.projects[e.target.dataset.project]=e.target.checked;save();}});
function closeCourse(){const note=document.getElementById('course-note');if(note&&currentCourse&&note.value!==String(record(currentCourse).note??'')){state.courses[currentCourse]={...record(currentCourse),note:note.value,updated:Date.now()};if(save())toast('笔记已自动保存');render();}dialog.close();}
document.getElementById('close-dialog').addEventListener('click',closeCourse);dialog.addEventListener('cancel',e=>{e.preventDefault();closeCourse();});dialog.addEventListener('click',e=>{if(e.target===dialog){const box=dialog.getBoundingClientRect();if(e.clientX<box.left||e.clientX>box.right||e.clientY<box.top||e.clientY>box.bottom)closeCourse();}});window.addEventListener('hashchange',()=>{render();const phase=new URLSearchParams(location.hash.split('?')[1]||'').get('phase');const section=phase!==null&&/^\d$/.test(phase)?main.querySelectorAll('.route-phase')[Number(phase)]:null;if(section)section.scrollIntoView({block:'start'});else window.scrollTo({top:0,behavior:'instant'});});render();

function validateProgressInput(input){if(!input||typeof input!=='object'||!getCourse(input.courseId)||!Number.isInteger(input.taskIndex)||input.taskIndex<0||input.taskIndex>=getCourse(input.courseId).topics.length||typeof input.completed!=='boolean')throw new Error('需要有效课程 ID、知识任务序号与完成状态。');return input;}
if(document.modelContext?.registerTool){
const lifecycle=new AbortController();
const registrations=[{
name:'list_learning_courses',title:'查看学习课程',description:'列出站内课程、先修关系和当前浏览器的学习进度。',inputSchema:{type:'object',properties:{query:{type:'string'}},additionalProperties:false},annotations:{readOnlyHint:true,untrustedContentHint:false},execute(input){if(!input||typeof input!=='object'||(input.query!==undefined&&typeof input.query!=='string'))throw new Error('搜索词必须为字符串。');const q=(input.query||'').toLowerCase();return COURSES.filter(c=>courseSearchText(c).includes(q)).map(c=>({id:c.id,name:c.name,phase:c.phase+1,prerequisites:c.prereqs,progress:pct(c),tasks:c.topics}));}
},{name:'set_learning_task_completion',title:'更新知识任务进度',description:'将某门课程的一个知识任务标记为已完成或未完成，并保存到当前浏览器。',inputSchema:{type:'object',properties:{courseId:{type:'string'},taskIndex:{type:'integer',minimum:0},completed:{type:'boolean'}},required:['courseId','taskIndex','completed'],additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:false},execute(input){const v=validateProgressInput(input),c=getCourse(v.courseId),entry=record(v.courseId);state.courses[v.courseId]={...entry,started:entry.started!==false,checks:c.topics.map((_,i)=>i===v.taskIndex?v.completed:entry.checks?.[i]===true)};const persisted=save();render();if(dialog.open&&currentCourse===v.courseId){updateCourseLearningControls();const checkbox=dialog.querySelector(`[data-check="${v.taskIndex}"]`);checkbox.checked=v.completed;checkbox.closest('label').classList.toggle('checked',v.completed);document.getElementById('check-count').textContent=state.courses[v.courseId].checks.filter(Boolean).length+' / '+c.topics.length;}return {courseId:v.courseId,taskIndex:v.taskIndex,completed:v.completed,progress:pct(c),persisted};}}];
for(const tool of registrations){try{Promise.resolve(document.modelContext.registerTool(tool,{signal:lifecycle.signal})).catch(()=>{});}catch{}}
window.addEventListener('pagehide',()=>lifecycle.abort(),{once:true});
}
